# Generated by Django 5.0.3 on 2024-11-07 00:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=20, unique=True, verbose_name='Número de cuenta')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo')),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('EUR', 'Euros'), ('PEN', 'Soles'), ('MXN', 'Pesos Mexicanos')], default='USD', max_length=3, verbose_name='Moneda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='InformeMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(unique=True, verbose_name='Mes')),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ingresos totales')),
                ('gastos_totales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Gastos totales')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Balance')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='chatbot_app.cuenta', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Informe Mensual',
                'verbose_name_plural': 'Informes Mensuales',
                'ordering': ['-mes'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(max_length=100, verbose_name='Fuente')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='chatbot_app.cuenta', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Límite')),
                ('gastado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Gastado')),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='chatbot_app.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('RETIRO', 'Retiro'), ('TRANSFERENCIA', 'Transferencia'), ('CONVERSION', 'Conversión de Moneda')], max_length=20, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('moneda_origen', models.CharField(blank=True, max_length=3, null=True, verbose_name='Moneda Origen')),
                ('moneda_destino', models.CharField(blank=True, max_length=3, null=True, verbose_name='Moneda Destino')),
                ('tasa_conversion', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tasa de Conversión')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='chatbot_app.categoria', verbose_name='Categoría')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='chatbot_app.cuenta', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
