# Generated by Django 5.0.3 on 2024-11-03 00:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0002_informemensual_ingreso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='informemensual',
            options={'verbose_name_plural': 'Informes Mensuales'},
        ),
        migrations.AlterModelOptions(
            name='ingreso',
            options={'verbose_name_plural': 'Ingresos'},
        ),
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'verbose_name_plural': 'Presupuestos'},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='informemensual',
            name='mes',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='categoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='chatbot_app.categoria'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='chatbot_app.categoria'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
