# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20241027-205933-plain-lot

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: es

pipeline:
  # Procesamiento base en español
- name: SpacyNLP
  model: "es_core_news_md"
- name: SpacyTokenizer
- name: SpacyFeaturizer

  # Extracción de características y entidades
- name: RegexFeaturizer
- name: RegexEntityExtractor
  case_sensitive: false
  use_lookup_tables: true
  use_regexes: true
- name: LexicalSyntacticFeaturizer

  # Vectorización de texto
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4

  # Extracción de entidades numéricas y temporales
##- name: DucklingHTTPExtractor
  # url: "http://localhost:8000"
  # dimensions: ["time", "number", "amount-of-money"]

  # Clasificación de intenciones y entidades
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
  entity_recognition: true
  intent_classification: true
  evaluate_on_number_of_examples: 20

  # Mapeo de sinónimos de entidades
- name: EntitySynonymMapper

  # Selector de respuestas
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true
  evaluate_on_number_of_examples: 20

  # Clasificador de fallback
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

# Políticas de diálogo
policies:
  # Política de memorización
- name: MemoizationPolicy
  max_history: 5

  # Política de memorización aumentada para conversaciones largas
- name: AugmentedMemoizationPolicy
  max_history: 6

  # Política basada en reglas
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true

  # Políticas de aprendizaje
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true

- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
  priority: 2

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
#policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
